### ISSUE TITLE
Mod ID with HoloInventory

### ISSUE THREAD

**Issue by sdaddy** [T145/metalchests#1]
### Expected Behavior

Should display "Iron Chest", "Gold Chest", etc.

### Actual Behavior

Displays tile.metalchests:metal_chest no matter which chest is used.

### Steps to Reproduce (including precondition)

Use HoloInventory 1.12.2-2.0.2.148 with MetalChests v1.2.2.g3d3d54b.

### Screenshot of this Problem

https://i.imgur.com/4Rudr5v.png

### Your Environment

- OS: Windows 10 Pro x64
- Minecraft version: 1.12.2
- MetalChests version: v1.2.2.g3d3d54b
- Forge version: 1.12.2-14.23.2.2624

**Comment by Boundarybreaker** [comment]
If the lang works for everything but HoloInventory, it's probably HoloInventory's problem.

**Comment by T145** [comment]
This is caused by how I manage the tiles. My system is much more efficient than the original IronChests, because I store it's "metal type" in its NBT instead of creating a whole tile entity. I'll look more into what HoloInventory does and see if I can't get the locale translated on my end w/out having to add direct support for HoloInventory.
