### ISSUE TITLE
Update deletes all items

### ISSUE THREAD

**Issue by angelnc1989** [T145/metalchests#16]
### Actual Behavior
Updating from v1.2.2 to any newer version makes chest invisible until rightclicked and deletes all items.

### Steps to Reproduce (including precondition)
1. Have some Metal Chests with items on v1.2.2
2. Update to v2.0.0 or v2.3.9

### Your Environment
- OS: Windows 10
- Full Forge version: 14.23.4.2749
- Mod version: v2.3.9

**Comment by T145** [comment]
This is probably just an issue on Forge's end. The earlier version was built on Forge version 1.12.2-14.23.4.2708, while the latest mod builds use 1.12.2-14.23.4.2747. You're using the latest Forge, so maybe something happened when switching. That's my best guess since there's nothing I can do on my end. All of the unlocalized names have remained constant. Try using JustEnoughIDs; It's another guess but it may help.
