### ISSUE TITLE
Crash on startup with only either Thaumcraft or Refined Relocation installed

### ISSUE THREAD

**Issue by angelnc1989** [T145/metalchests#24]
[Crashlog](https://pastebin.com/aRt6SWiy)

### Your Environment

- OS: Windows 10
- Full Forge version: 1.12.2, 14.23.4.2756
- Mod version: 2.9.5

**Comment by TakunSho** [comment]
To provide further information on this issue:

I'm getting a crash on server start due to the sorting hungry metal chest:

[Server: Refined Relocation + MetalChests](https://github.com/T145/metalchests/files/2299419/crash-2018-08-18_06.41.35-server.txt)

[Full Server Log](https://github.com/T145/metalchests/files/2299413/latest.log)

This is using:
Minecraft: 1.12.2
Forge: 2756
MetalChests: 2.9.5
Refined Relocation 2: 4.2.28
Thaumcraft: not installed

I have tried both with a fresh install, and with using the 2.5.7 config setting hungry chests to false

***
Client testing with only MetalChests, Refined Relocation 2, and Thaumcraft installed, I get a different error. If I disabled MetalChests, then the client booted without issue.
This is with adding Thaumcraft 6.1 Beta 22:
[Client: Thaumcraft + Refined Relocation + Metal Chests](https://github.com/T145/metalchests/files/2299420/crash-2018-08-18_06.51.39-client.txt)

**Comment by TakunSho** [comment]
Reviewing Angel's log, this error seems to present itself when Refined Relocation is installed but Thaumcraft is not. If neither mod is installed, MetalChests boots fine by itself. MetalChests + Thaumcraft gives the aforementioned Thaumcraft crash.

Using the 2.9.5 config file with both hungry and sorting hungry set to false does not resolve the issue, it still crashed with the first error.

**Comment by angelnc1989** [comment]
Yea, I have Refined Relocation, but no Thaumcraft.
