### ISSUE TITLE
[Feature Request] Double-chests

### ISSUE THREAD

**Issue by rallias** [T145/metalchests#6]
Currently, this mod provides only single blockspace chests. I think it would be cool if it provided the ability to put two of the same type of chest next to each other, and have them behave like the vanilla double chests, having both inventories accessible via the gui, or something similar to the InventoryLargeChest class.

**Comment by T145** [comment]
The reason why IronChests doesn't even do this is because that the inventories are generally larger than double chests anyway. The only intuitive way this could be added in would be to have a paging system created, so that you could just swap between each chest's individual inventory. Which still makes it kind of unintuitive, as you can just close the current chest and open its neighbor. I'll consider this for immersion purposes though.
